
#  MYSQL_CONNECTOR_INCLUDE_PATH, where to find mysql.h
#  MYSQL_CONNECTOR_LIBRARIES, the libraries needed to use MYSQL_CONNECTOR.
#  MYSQL_CONNECTOR_DIR_PATH, path to the MYSQL_CONNECTOR_LIBRARIES
#  MYSQL_EMBEDDED_LIBRARIES, the libraries needed to use MYSQL_CONNECTOR Embedded.
#  MYSQL_EMBEDDED_LIB_DIR, path to the MYSQL_EMBEDDED_LIBRARIES
#  MYSQL_FOUND, If false, do not try to use MYSQL_CONNECTOR.
#  MYSQL_EMBEDDED_FOUND, If false, do not try to use MYSQL_CONNECTOR Embedded.

include(CheckCXXSourceCompiles)

if(WIN32)
   find_path(MYSQL_CONNECTOR_INCLUDE_PATH mysql_connection.h
      PATHS
      $ENV{MYSQL_CONNECTOR}/include/jdbc/
   )
else(WIN32)
   find_path(MYSQL_CONNECTOR_INCLUDE_PATH mysql_connection.h
      PATHS
      $ENV{MYSQL_CONNECTOR}/include/jdbc/
   )
endif(WIN32)

if(WIN32)
   if (${CMAKE_BUILD_TYPE})
    string(TOLOWER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_TOLOWER)
   endif()

   if(CMAKE_BUILD_TYPE_TOLOWER MATCHES "debug")
      set(binary_dist debug)
      set(build_dist Debug)
   else(CMAKE_BUILD_TYPE_TOLOWER MATCHES "debug")
      ADD_DEFINITIONS(-DDBUG_OFF)
      set(binary_dist opt)
      set(build_dist Release)
   endif(CMAKE_BUILD_TYPE_TOLOWER MATCHES "debug")

   set(MYSQL_LIB_PATHS
      $ENV{MYSQL_CONNECTOR}/lib64
   )
   find_library(MYSQL_CONNECTOR_LIBRARIES NAMES mysqlcppconn
      PATHS
      ${MYSQL_LIB_PATHS}
   )
else(WIN32)
   set(MYSQL_LIB_PATHS
      $ENV{MYSQL_CONNECTOR}/lib64
   )
   find_library(MYSQL_CONNECTOR_LIBRARIES NAMES libmysqlcppconn
      PATHS
      ${MYSQL_LIB_PATHS}
   )
endif(WIN32)

find_library(MYSQL_EMBEDDED_LIBRARIES NAMES mysqld
   PATHS
   ${MYSQL_LIB_PATHS}
)

if(MYSQL_CONNECTOR_LIBRARIES)
   get_filename_component(MYSQL_CONNECTOR_DIR_PATH
 ${MYSQL_CONNECTOR_LIBRARIES} PATH)
endif(MYSQL_CONNECTOR_LIBRARIES)

if(MYSQL_EMBEDDED_LIBRARIES)
   get_filename_component(MYSQL_EMBEDDED_LIB_DIR ${MYSQL_EMBEDDED_LIBRARIES} PATH)
endif(MYSQL_EMBEDDED_LIBRARIES)

set( CMAKE_REQUIRED_INCLUDES ${MYSQL_CONNECTOR_INCLUDE_PATH} )
set( CMAKE_REQUIRED_LIBRARIES ${MYSQL_EMBEDDED_LIBRARIES} )

if(MYSQL_CONNECTOR_INCLUDE_PATH AND MYSQL_CONNECTOR_LIBRARIES)
   set(MYSQL_FOUND TRUE)
   message(STATUS "Found MYSQL_CONNECTOR: ${MYSQL_CONNECTOR_INCLUDE_PATH}, ${MYSQL_CONNECTOR_LIBRARIES}")
else(MYSQL_CONNECTOR_INCLUDE_PATH AND MYSQL_CONNECTOR_LIBRARIES)
   set(MYSQL_FOUND FALSE)
   message(STATUS "MYSQL_CONNECTOR not found.")
endif(MYSQL_CONNECTOR_INCLUDE_PATH AND MYSQL_CONNECTOR_LIBRARIES)

if(MYSQL_CONNECTOR_INCLUDE_PATH AND MYSQL_EMBEDDED_LIBRARIES AND HAVE_MYSQL_OPT_EMBEDDED_CONNECTION)
   set(MYSQL_EMBEDDED_FOUND TRUE)
   message(STATUS "Found MYSQL_CONNECTOR Embedded: ${MYSQL_CONNECTOR_INCLUDE_PATH}, ${MYSQL_EMBEDDED_LIBRARIES}")
else(MYSQL_CONNECTOR_INCLUDE_PATH AND MYSQL_EMBEDDED_LIBRARIES AND HAVE_MYSQL_OPT_EMBEDDED_CONNECTION)
   set(MYSQL_EMBEDDED_FOUND FALSE)
   message(STATUS "MYSQL_CONNECTOR Embedded not found.")
endif(MYSQL_CONNECTOR_INCLUDE_PATH AND MYSQL_EMBEDDED_LIBRARIES AND HAVE_MYSQL_OPT_EMBEDDED_CONNECTION)

mark_as_advanced(MYSQL_CONNECTOR_INCLUDE_PATH MYSQL_CONNECTOR_LIBRARIES MYSQL_EMBEDDED_LIBRARIES)
